app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  bot-url: ${BOT_URL}
  scheduler:
    enable: true
    interval: 30s
    force-check-delay: 15m
    batch-size: 100
    thread-count: 4
  access-type: ORM
  message-transport: kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    topic: ${KAFKA_TOPIC:test-topic}
    dlq-topic: ${KAFKA_BOT_TO_SCRAPPER_DLQ:bot-to-scrapper-dlq}
    bot-to-scrapper-topic: ${KAFKA_BOT_TO_SCRAPPER_TOPIC:bot-to-scrapper}

spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://postgres:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
