app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-url: ${SCRAPPER_URL}
  cache-ttl: 3000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    topic: ${KAFKA_TOPIC:link-updates}
    dlq-topic: ${KAFKA_DLQ_TOPIC:link-updates-dlq}
    commands-topic: ${KAFKA_BOT_TO_SCRAPPER:bot-to-scrapper}

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
